/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.unl;


import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;

import java.util.Iterator;
import javax.swing.JFileChooser;

import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JTextArea;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;

/**
 *
 * @author Lenovo
 */
public class main extends javax.swing.JFrame {

    JFileChooser seleccionar = new JFileChooser();
    File archivo;
    JTextArea txtConsola = new JTextArea();
    FileInputStream entrada;
    FileOutputStream salida;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
//        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
//        this.setSize((int) d.getWidth(), (int) d.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtarea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Universidad Nacional de Loja");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N

        jPanel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N

        jButton1.setText("Seleccionar Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.setText("Abrir...");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        txtarea.setEditable(false);
        txtarea.setColumns(20);
        txtarea.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        txtarea.setLineWrap(true);
        txtarea.setRows(5);
        txtarea.setAutoscrolls(false);
        txtarea.setFocusable(false);
        jScrollPane2.setViewportView(txtarea);

        jScrollPane1.setViewportView(jScrollPane2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addContainerGap(80, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //codigo hecho por Majito 
        if (seleccionar.showDialog(null, "Abrir") == JFileChooser.APPROVE_OPTION) {
            archivo = seleccionar.getSelectedFile();
            if (archivo.canRead()) {
                if (archivo.getName().endsWith("xlsx")) {
                    //String documento = abrirArchivo(archivo);
                    LeerEXCEL(archivo);
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    //codigo hecho por Majito
    public void LeerEXCEL(File archivo) {
        //XSSFWorkbook libro = new XSSFWorkbook();
        //String nombreArchivo = "C:/Users/Lenovo/Desktop/java.xlsx";
        String nombreArchivo = archivo.getAbsolutePath();
        System.out.println(archivo.getName());
        File excel = new File(nombreArchivo);
        List cellData = new ArrayList();
        try {
            //JTextArea txtConsola = new JTextArea();
            txtarea.append("Leyendo archivo " + nombreArchivo + "\n");

            FileInputStream fis = new FileInputStream(excel);
            XSSFWorkbook workBook = new XSSFWorkbook(fis);

            XSSFSheet hoja = workBook.getSheetAt(0);
            Iterator rowIterator = hoja.rowIterator();
            while (rowIterator.hasNext()) {
                //txtarea.append("*");
                XSSFRow row = (XSSFRow) rowIterator.next();
                Iterator iterator = row.cellIterator();
                List cellTemp = new ArrayList();
                while (iterator.hasNext()) {
                    XSSFCell cell = (XSSFCell) iterator.next();
                    cellTemp.add(cell);
                }
                txtarea.append("_");
                cellData.add(cellTemp);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        txtarea.append("100% \n");
        obtenerDatos(cellData,archivo);
    }

    public void obtenerDatos(List cellList,File archivo) {
        String rutaArchivo = archivo.getAbsolutePath();
        String hoja = "Majito";
        XSSFWorkbook libro = new XSSFWorkbook();
        XSSFSheet hoja1 = libro.createSheet(hoja);
        txtarea.append("Creando archivo \n");
        // Generar los datos para el documento        
        //txtarea.setForeground(Color.red);
        //String valorCelda="";
        double aleatorio ;
        for (int i = 0; i < cellList.size(); i++) {
            txtarea.append("*");
            List listado = (List) cellList.get(i);
            XSSFRow row = hoja1.createRow(i);
            for (int j = 0; j < listado.size(); j++) {                
                XSSFCell cell = row.createCell(j);
                XSSFCell celdas = (XSSFCell) listado.get(j);
                String valor = celdas.toString();
                //System.out.print(cellList.get(14)+","+listado.get(0)+"primera fila");
                if ((valor == "")&& (i > 4) ) {
                	aleatorio = Math.random()*1;
                        if(aleatorio > 0.5){
                            //valorCelda =String.valueOf(1);
                            cell.setCellValue(1);
                        }else{
                            //valorCelda =String.valueOf(0);
                            cell.setCellValue(0);
                        }                	
                    //cell.setCellValue(aleatorio);
                }else{
                 cell.setCellValue(valor);
                }
            }
            //System.out.println();
        }
        txtarea.append("100% \n");
        // Crear el archivo
        try (OutputStream fileOut = new FileOutputStream(rutaArchivo)) {
            //System.out.println("SE CREO EL EXCEL");
            txtarea.append("Archivo Generado con éxito \n");
            txtarea.append("En la ruta: \n" + rutaArchivo );
            libro.write(fileOut);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
//fin codigo hecho por Majito

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtarea;
    // End of variables declaration//GEN-END:variables
}
